[project]
name = "hub-task-python"
version = "0.1.0"
description = "backend task case, implement an http service that processes incoming requests"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi[standard]>=0.115.12",
]
